#!/usr/bin/python3
# python script to pull a specific discourse post by topic number
#
# you need to supply parameters base_url, api_username, and api_key
# in a file in cwd called "dc.yaml"
#
# you supply -t topic_number and -o output_file on the command line
#
# output_file will contain cleaned, editable discourse markup
# or HTML if the original file contained HTML
#
import subprocess, json, sys, getopt
from yaml import load, dump
try:
    from yaml import CLoader as Loader, CDumper as Dumper
except ImportError:
    from yaml import Loader, Dumper

def main(argv):
    topic = ''
    textfile = ''
    dash_t = False
    dash_o = False

    try:
        opts, args = getopt.getopt(argv,"ht:",["topic="])
    except getopt.GetoptError:
        print('dcbpull.py -t <topicnumber>')
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print('dcbpull.py -t <topicnumber>')
            sys.exit()
        elif opt in ("-t", "--topic"):
            dash_t = True
            topic = arg

    if(dash_t == False):
        print('missing required option "-t"')
        print('dcbpull.py -t <topicnumber>')
        sys.exit(3)

    config_file = open("/etc/dc.yaml","r")
    config_data = load(config_file, Loader=Loader)
    
#    f = open('topic.pull', 'w')
    proc = subprocess.Popen([
        'curl',
        '-X',
        'GET',
        '-H',
        'Api-Key: ' + config_data['api_key'],
        '-H',
        'Api-Username: ' + config_data['api_username'],
        '-H',
        'Content-Type: application/json',
        config_data['base_url'] + '/t/{'+str(topic)+'}.json'],
        stdout=subprocess.PIPE
    )
    output = proc.stdout.read()
    topic_json = json.loads(output)
#    f.write(str(topic_json))
    post_id = topic_json['post_stream']['posts'][0]['id']
    textfile = topic_json['post_stream']['posts'][0]['topic_slug'] + '-' + str(topic) + '.md'
    category_id = topic_json['category_id']
    if category_id != 5:
        sys.exit()
#    f2 = open('post.pull', 'w')
    proc2 = subprocess.Popen([
        'curl',
        '-X',
        'GET',
        '-H',
        'Api-Key: ' + config_data['api_key'],
        '-H',
        'Api-Username: ' + config_data['api_username'],
        '-H',
        'Content-Type: application/json',
        config_data['base_url'] + '/posts/{'+str(post_id)+'}.json'],
        stdout=subprocess.PIPE
    )
    output2 = proc2.stdout.read()
    post_json = json.loads(output2)
    raw = post_json['raw']
    f = open(textfile, "w")
    f.write(str(raw))

if __name__ == "__main__":
    main(sys.argv[1:])


