.\" manpage for dpub
.\" Contact wowear@gmail.com to correct errors or typos
.TH dpub 7 "26 June 2020" "version 0.8" "dpub manpage"
.SH NAME
dpub - edit and publish discourse topics
.SH SYNOPSIS
.B dpub
.RI "[" OPTION "]..."
.SH DESCRIPTION
.B dpub
gets, puts, and creates topics to/from discourse using the discourse API. It
converts between discourse markdown and JSON, as appropriate to the other options
selected.  It will not get a discourse topic that has been deleted.
.PP
The markdown files retrieved from discourse by
.B dpub
.RI "can be freely edited, as long as discourse markdown is retained."
These edited files can then reposted over the existing text by using the same topic number when putting them back, or used to create a new file, with topic number assigned
by discourse when the new topic is created.
.PP
.B dpub
.RI "is written in python; it requires at least python3 to be installed on the system where it will be used."
.SH OPTIONS
.TP
.B -a, --autoname
Pull the TOPIC specified by -t and place it into a file whose name is based on the TOPIC title and topic number.
.TP
.B -c, --category CATEGORY
Operate only on TOPICs in CATEGORY.  Any specified topics that do not match this category will be ignored.
.TP
.B -f <FILENAME>, --file=FILENAME
Sets the filename to be read (-p, -c) or written (-g) as part of the specified
operation.
.TP
.B -g, --get
Read a numbered TOPIC into FILENAME; requires -t TOPIC and -f FILENAME.
.TP
.B -G
Get (-g) or put (-p) a markdown file whose title is indicated with -T and whose topic is -t; user must be in the an already prepared offline git directory
.TP
.B -h
Prints program usage information and exits
.TP
.B -k <CONFIG_FILE>, --config=CONFIG_FILE
Sets the yaml configuration file that contains the discourse URL, the user's api-key,
and the user's name for authentication purposes.  See FILES for a description of the
required format.
.TP
.B -j <JSON_FILE>, --json=JSON_FILE
Causes
.B dpub
to output the
.B post
.RI "JSON-encoded data to JSON_FILE before converting it to markdown.  Works only with the"
.B -g
option.
.PP
.TP
.B -J <TOPIC_JSON_FILE>, --JSON=TOPIC_JSON_FILE
Causes
.B dpub
to output the
.B topic
.RI "JSON-encoded data to TOPIC_JSON_FILE before converting it to markdown.  Works only with the"
.B -g
option.
.TP
.B -n, --new
Create a new topic and write FILENAME to it; requires -f FILENAME.
.TP
.B -p, --put
Write FILENAME to TOPIC number; requires -t TOPIC and -f FILENAME.
.TP
.B -r, --srange <TOPIC_NUMBER>
Specify the minimum topic to be pulled in a range of topics; -a option implied. -R must also be set.
.TP
.B -R, --erange <TOPIC_NUMBER>
Specify the maximum topic to be pulled in a range of topics; -a option implied. -r must also be set.
.TP
.B -t, --topic <TOPIC_NUMBER>
Specify the TOPIC number to be used by dpub.
.TP
.B -T, --topic_title <TOPIC_TITLE>
Specify the TOPIC number to be used by dpub.
.SH FILES
.TP
.B dc.yaml
Contains the information necessary to authenticate to the correct discourse API:
.PP
.RS
.BR base_url: https://discourse.<subdomain>.<suffix>
.br
.BR api_username: <your_username>
.br
.BR api_key: <api-key string....................................>
.RE
.TP
.B <topic-name-slug-###>
The file name resulting from the -a command consists of the topic "slug" (the words of the topic name, stripped of punctuation and separated by dashes), with the topic number appended to the end of the filename.
.SH BUGS
Currently, the code does not check whether the user input more than one of the mutually
exclusive options
.B -g
/
.B -p
/
.B -c
.RI "on the same command line.  As a consequence, the behavior when specifying more than one of these options is unpredictable."
.SH AUTHOR
Bill Wear wowear@gmail.com
.SH COPYRIGHT
MIT License
.PP
Copyright (c) 2020 Bill Wear
.PP
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
